- hosts: all
  gather_facts: no
  vars:
     ansible_connection: local
     ansible_python_interpreter: "{{ansible_playbook_python}}"
  vars_files:
    - inventory/gns3_vars.yml
  collections:
    - davidban77.gns3
  tasks:
    - name: Generate boiler plate config files
      when: boiler_plate.config == "generate" and ansible_net_os != "gns3_builtin"
      block:
        - name: Create build folder
          file:
            path: "{{ playbook_dir }}/build"
            state: directory

        - name: Generate config
          template:
            src: templates/{{ ansible_net_os }}.j2
            dest: "{{ playbook_dir }}/build/{{ inventory_hostname }}-{{ ansible_net_os }}.conf"
