---
- hosts: localhost
  gather_facts: no
  vars_files:
    - inventory/gns3_vars.yml
  collections:
    - davidban77.gns3

  tasks:
    - name: Lab creation and setup
      when: execute == "create"
      block:
        - import_role:
            name: create_lab

        - name: Collect the nodes inventory
          gns3_nodes_inventory:
            url: "{{ gns3_url }}"
            project_name: "{{ gns3_project_name }}"
          register: nodes_inventory

        - debug: var=nodes_inventory

        - name: Pause section
          when: boiler_plate.config == "deploy" and automated_push == "no"
          pause:
            prompt: "Press Enter to proceed with configuration deployments:"

        - name: Pause section
          when: boiler_plate.config == "deploy" and automated_push == "yes"
          pause:
            minutes: "{{ gnse_push_delay | default(3) }}"

    - name: Stop lab and deletion
      when: execute == "delete"
      block:
        - import_role:
            name: delete_lab

- name: Run configuration playbook
  import_playbook: config_play.yml
  when: execute=="create"
